<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<script type="text/javascript">
var customer_status 	= "<?php echo Mage::getSingleton('customer/session')->isLoggedIn() ?>";
var url_busca_cep 		= "<?php echo Mage::getUrl('onestepcheckout/index/buscaCep') ?>";
var url_indetify		= "<?php echo $this->getUrl('onestepcheckout/index/IdentifyUser') ?>";
var url_authenticate 	= "<?php echo $this->getUrl('onestepcheckout/index/authenticate') ?>";



var url_save_shipping 			= "<?php echo Mage::getUrl('onestepcheckout/index/saveShipping')?>";
var url_save_billing 			= "<?php echo Mage::getUrl('onestepcheckout/index/saveBilling')?>";
var url_save_shipping_method 	= "<?php echo Mage::getUrl('onestepcheckout/index/saveShippingMethod')?>";
var url_save_payment_metthod 	= "<?php echo Mage::getUrl('onestepcheckout/index/savePaymentMethod')?>";

var form_post_create  			= "<?php echo Mage::getUrl('onestepcheckout/index/formPostCreate')?>";
var url_new_address  			= "<?php echo Mage::getUrl('onestepcheckout/index/NewAddress')?>";
var url_clear_identify 			= "<?php echo Mage::getUrl('onestepcheckout/index/ClearIdentifyUser')?>";
var updateemailmsg 		= "<?php echo Mage::getUrl('onestepcheckout/index/updateemailmsg')?>";
var is_virtual			= "<?php echo Mage::helper('onestepcheckout')->onlyProductDownloadable() ?>";



jQuery(function(){
	Setmask();
	AddValidateFormCreate();
    jQuery("#onestep_form_identify").on("submit", function(e){
        IdentifyUser();
        e.preventDefault();
    });
});
</script>
