<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<script type="text/javascript">
var customer_status = "<?php echo Mage::getSingleton('customer/session')->isLoggedIn() ?>";
var buscacepurl = "<?php echo Mage::getUrl('onestepcheckout/index/buscaCep') ?>";
var updateemailmsg = "<?php echo Mage::getUrl('onestepcheckout/index/updateemailmsg')?>";
var is_virtual = 	"<?php echo Mage::helper('onestepcheckout')->onlyProductDownloadable() ?>";
jQuery(document).ready(function(){
	ChangeEvents();
	Setmask();
	jQuery('#billing\\:customer_password').on('input',function(e){
		jQuery('#billing\\:confirm_password').val(jQuery('#billing\\:customer_password').val());
	});

	jQuery('#init-account').bind("click",function(e){
		e.preventDefault();

		var form = new VarienForm('onestep_form_account', true);
		if(form.validator.validate())	{
			visibilyloading();
			var email = jQuery('#billing\\:email').val();
			jQuery.ajax({
					type: "POST",
					url: "<?php echo Mage::getUrl('onestepcheckout/index/updateemailmsg')?>",
					data:"email="+email,
					success: function(msg){
						if(msg==0){
							return false;
						}else{
							jQuery( "#onestep_form_account" ).submit();
						}
					}
				});
		} else 	{
			jQuery(".erros_cadastro_valores").html("");
			var erro_dado = [];
			var j = 0;
			jQuery(".validation-failed").each(function() {
				j++;
				temp_erro = jQuery(this).attr("title");
				if(jQuery.inArray(temp_erro, erro_dado) != 1){
					erro_dado[j] = jQuery(this).attr("title");
					jQuery(".erros_cadastro_valores").append('<li>'+erro_dado[j]+'</li>');
				}
			});
		
			jQuery('#ErrosFinalizacao').modal();

			return false;
		}
	});
});
</script>
