<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>

<script type="text/javascript">
//<![CDATA[


(function($) {

var buscacepurl = "<?php echo Mage::getUrl('Transparente/Standard/buscaCep') ?>";

logined = function()
{
	<?php	if(Mage::getSingleton('customer/session')->isLoggedIn()):?>
		return 1;
	<?php else: ?>
		return 0;
	<?php endif ?>
}
ProxCamp = function(fields) {
	fields.value=soNumeros(fields.value)
	if (fields.value.length == fields.maxLength) {
			for (var i = 0; i < fields.form.length; i++) {
				if (fields.form[i] == fields && fields.form[(i + 1)] && fields.form[(i + 1)].type != "hidden") {
					fields.form[(i + 1)].focus();
				break;
			}
		}
	}
};



soNumeros = function(v){
    return v.replace(/\D/g,"")
};





getval = function(sel) {
	if (sel.value == 1){
		jQuery('.dados-pj').slideUp();
		jQuery('.dados-pj input:not([type=checkbox])').removeClass('required-entry');
	}else{
		jQuery('.dados-pj').slideDown();
		jQuery('.dados-pj input:not([type=checkbox])').addClass('required-entry');
	}
};

marcar_isento = function() {
	jQuery("#insestadual").val("Isento");
};


buscarEndereco = function(whatform) {
	if (whatform == "billing") {
		jQuery(".hide-zip-code").removeClass("hide-zip-code");
		var campos = {
			postcode: document.getElementById('billing:postcode'),
			street_1: document.getElementById('billing:street1'),
			street_4: document.getElementById('billing:street4'),
			city: document.getElementById('billing:city'),
			region: document.getElementById('billing:region_id')
		};

	}
	if (whatform == "shipping") {
		var campos = {
			postcode: document.getElementById('shipping:postcode'),
			street_1: document.getElementById('shipping:street1'),
			street_4: document.getElementById('shipping:street4'),
			city: document.getElementById('shipping:city'),
			region: document.getElementById('shipping:region_id'),
		};

	}
	if (whatform == "register") {
		var campos = {
			postcode: document.getElementById('postcode'),
			street_1: document.getElementById('street_1'),
			street_4: document.getElementById('street_4'),
			city: document.getElementById('city'),
			region: document.getElementById('region_id')
		};
	}

	jQuery.ajax({
		type:'GET',
		url:  buscacepurl+'meio/cep/cep/' + campos.postcode.value.replace(/\+/g, ''),

		beforeSend: function(data){
			jQuery(campos.street_1).attr('placeholder', 'Buscando Endereço');
			jQuery(campos.street_4).attr('placeholder', 'Buscando Endereço');
			jQuery(campos.city).attr('placeholder', 'Buscando Endereço');
		},

		success: function(data){
			jQuery('#loading-mask').fadeOut();
			jQuery("#billing\\:street2").focus();
			if(data){
				var addressData = jQuery.parseJSON(data);
				if(addressData.logradouro != "undefined"){
					jQuery(campos.street_1).attr('placeholder', 'Rua');
					jQuery(campos.street_2).attr('placeholder', 'N.º');
					jQuery(campos.street_4).attr('placeholder', 'Bairro');
					jQuery(campos.city).attr('placeholder', 'Cidade');
					jQuery(campos.street_1).val(addressData.logradouro);
					jQuery(campos.street_4).val(addressData.bairro);
					jQuery(campos.city).val(addressData.cidade);
					jQuery(campos.region).val(addressData.ufid);

				}else {
					jQuery(campos.street_1).val('');
					jQuery(campos.street_4).val('');
					jQuery(campos.city).val('');
					jQuery(campos.street_1).attr('placeholder', 'Rua');
					jQuery(campos.street_2).attr('placeholder', 'N.º');
					jQuery(campos.street_4).attr('placeholder', 'Bairro');
					jQuery(campos.city).attr('placeholder', 'Cidade');
				}
				
				
			} else {
				jQuery(campos.street_1).attr('placeholder', 'Rua');
				jQuery(campos.street_2).attr('placeholder', 'N.º');
				jQuery(campos.street_4).attr('placeholder', 'Bairro');
				jQuery(campos.city).attr('placeholder', 'Cidade');
				
			}
		},
		error: function(){
			jQuery(campos.street_1).val("");
			jQuery(campos.street_4).val("");
			jQuery(campos.city).val("");
			jQuery(campos.region).val("");
			
		},
	});
};



showcreateAccount = function(){
	jQuery("#cadastrar").removeClass('force-nodisplay');
	
	jQuery("#criar_loga").hide();
};


checkedLoginStep = function(val){
	jQuery('#loading-mask').show();
	jQuery.ajax({
			async:false,
			type: "POST",
			url: "<?php echo Mage::getUrl('onestepcheckout/index/updateemailmsg')?>",
			data:"email="+val,

			success: function(msg){
				
					if(msg==0){
						jQuery('#loading-mask').hide();
						jQuery('.pre-step').hide();
						jQuery('#login-checked').show();
						jQuery('#login-checked').removeClass('no-display');
						jQuery('#checked-login-email').val(val);

					}else{
						jQuery('#loading-mask').hide();
						jQuery('.pre-step').hide();
						jQuery('#billing\\:email').val(val);
						jQuery('#create-checked').removeClass('no-display');
						jQuery('#create-checked').show();
					}					
				
			}
		});
}
updateEmailmsg = function(val){

	jQuery.ajax({
			type: "POST",
			url: "<?php echo Mage::getUrl('onestepcheckout/index/updateemailmsg')?>",
			data:"email="+val,
			
			success: function(msg){
				val=jQuery('#billing\\:email').val();
				emailvalidated=Validation.get('IsEmpty').test(val) || /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(val);
				
				var error="<div id=\"message-box\"><div  class=\"validation-advice\" style=\"position:relative;\">Email já cadastrado, por favor <a href=\"#\" data-toggle=\"modal\" data-target=\"#loginModel\"  id=\"loginbox\">Clique aqui e faça o login</a></div></div>";
				if(msg==0){
					jQuery('#billing\\:email').after(error);
					jQuery('#message-box').html(error);
					return 0;

				}else{
					if(logined()!=1){
						jQuery('#message-box').html('');
					}
					jQuery('#billing\\:email').removeClass('validation-failed');
					return 1;
				}
			}
		});
}



})(jQuery);



jQuery(document).ready(function(){
	ChangeEvents();
	Setmask();

	jQuery('#init-account').bind("click",function(e){
		e.preventDefault();

		var form = new VarienForm('onestep_form_account', true);

		if(form.validator.validate())	{
			var email = jQuery('#billing\\:email').val();
			jQuery.ajax({
					type: "POST",
					url: "<?php echo Mage::getUrl('onestepcheckout/index/updateemailmsg')?>",
					data:"email="+email,
					
					success: function(msg){
						
						if(msg==0){
							return false;

						}else{
							jQuery('#loading-mask').show();
							jQuery( "#onestep_form_account" ).submit();
						}
					}
				});
				
			

		} else 	{
			jQuery(".erros_cadastro_valores").html("");
			var erro_dado = [];
			var j = 0;
			jQuery(".validation-failed").each(function() {
				j++;
				temp_erro = jQuery(this).attr("title");
				if(jQuery.inArray(temp_erro, erro_dado) != 1){
					erro_dado[j] = jQuery(this).attr("title");
					jQuery(".erros_cadastro_valores").append('<li>'+erro_dado[j]+'</li>');
				}


			});
		
			jQuery('#ErrosFinalizacao').modal('toggle');

			return false;
		}
		
	});


	
	

	



});

	
//]]>
</script>
