<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<script type="text/javascript">
var message_payment 			= "Por Favor, selecione um meio de pagamento.";
var message_ship 				= "Por favor, selecione um Meio de Envio";
var url_save_shipping 			= "<?php echo Mage::getUrl('onestepcheckout/index/saveShipping')?>";
var url_save_billing 			= "<?php echo Mage::getUrl('onestepcheckout/index/saveBilling')?>";
var url_save_shipping_method 	= "<?php echo Mage::getUrl('onestepcheckout/index/saveShippingMethod')?>";
var url_save_payment_metthod 	= "<?php echo Mage::getUrl('onestepcheckout/index/savePaymentMethod')?>";
var url_busca_cep 				= "<?php echo Mage::getUrl('onestepcheckout/index/buscaCep') ?>";
var form_post_address  			= "<?php echo Mage::getUrl('onestepcheckout/index/formPostAddress')?>";
var url_new_address  			= "<?php echo Mage::getUrl('onestepcheckout/index/NewAddress')?>";
var checkoutsuccess = "<?php echo Mage::getUrl('checkout/onepage/success')?>";

var updatecouponurl = "<?php echo Mage::getUrl('onestepcheckout/index/updatecoupon')?>";
var updateqtyurl = "<?php echo Mage::getUrl('onestepcheckout/index/updateqty')?>";
var removeproducturl = "<?php echo Mage::getUrl('onestepcheckout/index/removeproduct')?>";
var updateordermethodurl = "<?php echo Mage::getUrl('onestepcheckout/index/updateordermethod') ?>";

var address_status = "<?php echo Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling() ?>";
var is_virtual = 	"<?php echo Mage::helper('onestepcheckout')->onlyProductDownloadable() ?>";
var set_payment_form =	 "<?php echo $this->getUrl('checkout/onepage/savePayment') ?>";
var customer_status = "<?php echo Mage::getSingleton('customer/session')->isLoggedIn() ?>";


Validation.add('validate-tel-national', 'Entre com telefone válido: (99)9999-9999 ou caso tenha o 9º digito (99)9999-99999',function(v) {
		return Validation.get('IsEmpty').test(v) || /^([()])([0-9]){2}([)])([0-9]){4,5}([-])([0-9]){4,5}$/.test(v);
	});
Validation.add('validate-cel-national', 'Entre com telefone válido: (99)9999-9999 ou caso tenha o 9º digito (99)9999-99999', function(v) {
		return Validation.get('IsEmpty').test(v) || /^([()])([0-9]){2}([)])([0-9]){5}([-])([0-9]){4}$/.test(v);
	});
Validation.add('validate-zip-international', 'Entre com um cep válido: 99999-999', function(v) {
		return Validation.get('IsEmpty').test(v) || /^([0-9]){5}([-])([0-9]){3}$/.test(v);
	});

(function($) {
	jQuery(document).ready(function(){
		if(!address_status){
			EditAddress(0, "new");
		} 
		ChangeEvents();	
		Setmask();
		
		if(!is_virtual){
			jQuery('#moip_cc_number, #moip_cc_cid, #moip_cc_owner').focus(function() {
				var selectShipping = jQuery("input[name='shipping_method']:checked").val();
				if(typeof selectShipping == 'undefined'){
					jQuery('.bg-payment-method').html('<div class="select-shipping-for-payment"><div class="icon-large"><span class="glyphicon glyphicon-upload" aria-hidden="true"></span></div><div class="text-select-shipping-for-payment">Para calcularmos o valor total, <strong>escolha acima o método de envio</strong></div></div>');
				}
			});
		}

	});	
})(jQuery);
</script>

