<?php $info = $this->_prepareInfo(); ?>


<?php if(is_array($info)): ?>
		
		
		<?php $url = $info["raw_details_info"]["_links"]["boleto"]["redirect_href"].'/print' ?>
		
		<div class="box-content">
				<p>Boleto Bancário - Recorrente</p>
				<p><a  class="button btn-checkout btn-default" title="Finalizar compra"  href="<?php echo  $url  ?>"  target="_blank" style="max-width: 200px;">Imprimir Boleto</a></p>
		</div>
<?php else: ?>
	<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<?php endif; ?>