          <form role="form" action="<?php echo Mage::getUrl('Transparente/index/LoginOnclick', array('_secure' => true )) ?>" method="post" id="onclick_login">
          	<div class="progress-login" style="display:none;">
      			  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width:100%">
      			   	Estamos realizando sua autenticação.
      			  </div>
			     </div>
      			<div class="form-post-loading-login">
              <div id="error-login-onclick"></div>
      				<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
      			         <div class="loading">
      			          	 <div class="form-group">
                            <label for="usrname"><span class="glyphicon glyphicon-user"></span> E-mail</label>
                            <input type="text" name="email" class="input-text required-entry validate-email form-control" id="usrname" placeholder="Digite seu email">
                          </div>
                          <div class="form-group">
                            <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Senha</label>
                            <input type="password"  class="input-text required-entry form-control" id="login-password" name="password" placeholder="Senha">
                          </div>
      			            <button type="button" id="moip-onclick" class="btn btn-success btn-block" onclick="onclick_login_form.submit(this)"><span><span>Entrar</span></span></button>
      			         </div>
      			</div>
          	
          </form>
        

<script type="text/javascript">

  
      var onclick_login_form = new VarienForm('onclick_login');

    onclick_login_form.submit = function (button, url) {
        if (this.validator.validate()) {
            var form = this.form;
           
            var data = jQuery('#onclick_login').serialize();
           
            try {
              //jQuery(".form-post-loading").hide();
              jQuery(".progress").show();
                jQuery.ajax({
                      url: form.action,
                      dataType: 'json',
                      type : 'post',
                      data: data,
                      success: function(data){
                        if(data._status == "SUCCESS"){
                          jQuery(".progress-login").hide();
                          jQuery(".form-post-loading-login").hide();
                          jQuery('#response-moip-onclick-payment').replaceWith(data.mensage);  
                        } else {
                          jQuery(".progress-login").hide();
                          jQuery(".form-post-loading-login").show();
                          jQuery('#error-login-onclick').replaceWith(data.mensage);  
                        }
                        
                      }
                });
            } catch (e) {
            }
          

          
        }
    }.bind(onclick_login_form);

</script>


