<?php $cofre = $this->getCofre(); ?>

<?php if($cofre != "false"): ?>
    <?php $_i = 0; ?>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <h2  class="onclick-title">Pagamento</h2>
        <?php $decode = json_decode($cofre, true); ?>
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="form-group">
                <label>Escolha o seu Cartão</label>
                <?php foreach ($decode  as $key => $value): ?>
                <?php $cardBrand = $value['moip_card_brand'] ?>
                <?php $cardNunber = $value['moip_card_id'] ?>
                        <div class="list-group-item">
                            <div class="titular-moip-onclick"><?php echo $value['moip_card_fullname']; ?></div>
                            <label>
                                <input id="payment_card_cofre" type="radio" title="Selecione o Cartão de Crédito Salvo" class="validate-one-required-by-name" 
                                name="moip_cc_cofre_nb"  value="<?php echo $cardNunber ?>" <?php if($_i==0): ?> checked="checked"<?php endif;?>>
                                <?php echo$value['moip_card_brand']; ?> - <?php echo $value['moip_card_first6'] ?> ** **** <?php echo $value['moip_card_last4'] ?>
                                
                            </label>
                        </div>
                        <?php $_i++; ?>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 no-padding">
            <div class="form-group">
               <label for="psw">Cod. de Segurança</label>
                <input type="text" class="form-control required-entry" name="moip_cc_cofre_id" id="moip_cc_cofre_id" placeholder="Código de Segurança">
            </div>
            <div class="form-group">
                      <label for="psw">Parcelas</label>
                      <div id="update-parcelas"><?php echo $this->getChildParcealas() ?></div>
            </div>
        </div>
    </div>
    <div class="clearfix">
        <button type="button" id="moip-onclick" class="btn btn-success btn-block" onclick="onclick_proccess_form.submit(this)"><span><span>Finalizar Pedido</span></span></button>
    </div>
<?php else: ?>
     <div class="clearfix">
    <h2  class="onclick-title"><span class="glyphicon glyphicon-credit-card"></span> Pagamento</h2>
        <ul class="messages"><li class="error-msg"><ul><li><span>Desculpe, mas ainda não temos nenhum cartão salvo por você! :(</span></li></ul></li></ul>
        <p>Por favor, cadastre o seu cartão realizando um novo pedido salvando o seu cartão no checkout."</p>
        <a href="<?php echo Mage::helper('checkout/url')->getCheckoutUrl(); ?>" class="btn btn-success btn-block">Cadastrar seu Cartão</a>
    </div>
<?php endif; ?>