  <?php 
   	$request = $this->getRequest();
	$module = $request->getModuleName();
	$controller = $request->getControllerName();
	$action = $request->getActionName();
	
	if($action == "cadastro") {
		$step1 = "active";
		$step2 = "disabled";
		$step3 = "disabled";
	} elseif ($action == "index") {
		$step1 = "complete";
		$step2 = "active";
		$step3 = "disabled";
	} elseif ($action == "redirect"){
		$step1 = "complete";
		$step2 = "complete";
		$step3 = "active";

	}
 ?>
   <div class="row bs-wizard hidden-xs">
                
                <div class="col-xs-6 bs-wizard-step <?php echo $step1 ?>">
                  <div class="text-center bs-wizard-stepnum ">Identificação</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <span class="bs-wizard-dot"></span>
                </div>
                
                <div class="col-xs-6 bs-wizard-step <?php echo $step2 ?>"><!-- complete -->
                  <div class="text-center bs-wizard-stepnum">Entrega & Pagamento</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <span class="bs-wizard-dot"></span>
                </div>
                
               
    </div>