<div class="box-content">
	<?php if(Mage::app()->getRequest()->getControllerModule() != "Mage_Checkout" && Mage::app()->getRequest()->getActionName() != "progresscheckout"): ?>

		<?php $brand =  $this->getBrand(); ?>
		<?php if(isset($brand)): ?>	
			<h3 class="h3"><?php echo $this->getBrand(); ?></h3>
			<div>
				<?php echo  Mage::helper('transparente')->__('<strong>%s</strong>', $this->getFullname() ); ?>
			</div>
			<?php $installment = $this->getInstallment(); ?>
			<?php if($installment > 1): ?>
				<div>
					<?php echo Mage::helper('transparente')->__('%s parcelas', $installment); ?>
				</div>
			<?php endif; ?>
			<div>
				<?php echo  Mage::helper('transparente')->__('<strong>%sxxxxx%s</strong>', $this->getFirst6(), $this->getLast4() ); ?>
			</div>
			<div>
				<a  class="h3" title="Finalizar compra" href="<?php echo  $this->viewInMoip()   ?>">
					<?php echo Mage::helper('transparente')->__('Veja detalhes do pedido na conta Moip'); ?>
				</a>
			</div>
		<?php else: ?>
				<?php echo Mage::helper('transparente')->__('Não foi possível recuperar a informação do pagamento.'); ?>
		<?php endif; ?>
		
	<?php else: ?>
		<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
	<?php endif; ?>
</div>