<div class="page-title">
	<h2><?php echo $this->__('Forma de <strong>Envio</strong>') ?></h2>
</div>

<div class="row">
	<?php echo $this->getChildHtml('available') ?>
</div>
<div class="progress hidden-it" id="shipping-progress">
    <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
        Atualizando Métodos de Envio
    </div>
</div>