<?php
/* Mage::getModel("sales/order")->getCollection()->getLastItem()->getIncrementId(); */
if(Mage::app()->getRequest()->getModuleName() != "onestepcheckout" && Mage::app()->getRequest()->getModuleName() != "checkout"){
?>
<?php $info = $this->_prepareInfo(); ?>
<?php $meio = $info['forma_pagamento'];?>

	<?php if($meio == "CartaoCredito"): ?>


		<div class="box-content">
			<h3><?php echo $info['moip_card_brand']; ?> <b><?php echo $info['moip_card_installment']; ?><b> parcelas</h3>
			<div class="input-value">
				<?php echo $info['moip_card_fullname'] ?>
			</div>

			<div class="input-value">
				<label>6 Primeiros dígitos do cartão</label>
				<?php echo $info['moip_card_first6'] ?>
			</div>

			<div class="input-value">
				<label>4 Últimos dígitos do cartão</label>
				<?php echo $info['moip_card_last4'] ?>
			</div>


			<div class="input-value">
				<label>Data de Nascimento do Titular</label>
				<?php echo $info['moip_card_birthdate'] ?>
			</div>

			<div class="input-value">
				<label>Pagamento n.º</label>
				<?php echo $info['moip_pay'] ?>
			</div>

		</div>

	<?php endif ?>

	<?php if($meio == "BoletoBancario"): ?>
		<div class="box-content">
				<p>Boleto Bancário</p>
				<p><a  class="button btn-checkout btn-default" title="Finalizar compra"  href="<?php echo  $info['moip_href_boleto']  ?>"  target="_blank">Imprimir Boleto</a></p>
				<p>Código de Barras</p>
				<p><input type="text" value="<?php echo $info['moip_linecode_boleto'] ?>" readonly="disable"></p>
				<p>Vencimento: <?php echo date('d-m-Y', strtotime($info['moip_expiration_boleto'])) ?></p>

		</div>
	<?php endif ?>

	<?php if($meio == "DebitoBancario"): ?>
		<p>Transferência Bancária</p>
		<p><a  class="button btn-checkout btn-default" title="Finalizar compra"  href="<?php echo  $info['moip_href_trans']  ?>"  target="_blank">Ir Ao banco</a></p>


		</div>
	<?php endif ?>


<?php } else { ?>

<?php $addtional = $this->getMethod()->getInfoInstance()->getAdditionalData();?>
<?php $addtional = unserialize($addtional); ?>
<?php if($addtional['formapagamento_moip'] == "CartaoCredito"): ?>
	<?php echo Mage::helper('transparente')->__('Nome Impresso no cartão: %s', $this->htmlEscape($this->getInfo()->getCcOwner())) ?><br/>
	<?php echo Mage::helper('transparente')->__('Bandeira: %s', $this->htmlEscape($this->getNomeBrand($this->getInfo()->getCcType()))) ?><br/>
	<?php echo Mage::helper('transparente')->__('Número do cartão: xxxx-%s', $this->htmlEscape($this->getInfo()->getCcLast4())) ?><br/>
	<?php echo Mage::helper('transparente')->__('Vencimento do cartão: %s/%s', $this->htmlEscape($this->getInfo()->getCcExpMonth()), $this->htmlEscape($this->getInfo()->getCcExpYear())) ?><br/>

<?php else: ?>
<?php echo $addtional['formapagamento_moip'] ?>
<?php endif; ?>

<?php } ?>