<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<script type="text/javascript">
var form_post_address  			= "<?php echo Mage::getUrl('onestepcheckout/index/formPostAddress')?>";
var url_new_address  			= "<?php echo Mage::getUrl('onestepcheckout/index/NewAddress')?>";
var url_busca_cep 				= "<?php echo Mage::getUrl('onestepcheckout/index/buscaCep') ?>";
var address_status = "<?php echo Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling() ?>";
var is_virtual = 	"<?php echo Mage::helper('onestepcheckout')->onlyProductDownloadable() ?>";
var customer_status = "<?php echo Mage::getSingleton('customer/session')->isLoggedIn() ?>";


Validation.add('validate-tel-national', 'Entre com telefone válido: (99)9999-9999 ou caso tenha o 9º digito (99)9999-99999',function(v) {
		return Validation.get('IsEmpty').test(v) || /^([()])([0-9]){2}([)])([0-9]){4,5}([-])([0-9]){4,5}$/.test(v);
	});
Validation.add('validate-cel-national', 'Entre com telefone válido: (99)9999-9999 ou caso tenha o 9º digito (99)9999-99999', function(v) {
		return Validation.get('IsEmpty').test(v) || /^([()])([0-9]){2}([)])([0-9]){5}([-])([0-9]){4}$/.test(v);
	});
Validation.add('validate-zip-international', 'Entre com um cep válido: 99999-999', function(v) {
		return Validation.get('IsEmpty').test(v) || /^([0-9]){5}([-])([0-9]){3}$/.test(v);
	});


	jQuery(document).ready(function(){
		
		
		Setmask();
		
	});	

</script>

