<?php
$_order = Mage::registry('current_order');
//$_order = $this->getOrder() ;
$orderid=$_order->getId();
$orders=Mage::getModel('onestepcheckout/onestepcheckout')->getCollection()->addFieldToFilter('sales_order_id',$orderid);
$class_orders=get_class($orders);	
$o ='';

foreach($orders as $order)	
{
	$o = $order; break;		
}
?>

<div class="col2-set generic-box">
    <div class="">
        <h4><?php echo $this->__('Comentáriso do Pedido') ?></h4>
        <span><?php if($o):?><?php echo $o->getMoipCustomercommentInfo(); ?><?php endif?></span>
    </div>
</div>