<div  class="col-md-8 col-md-offset-2">
	<div class="page-title">
		<h2>Você já tem um cadastro, <strong>acesse sua conta</strong>
			<span class="goback">
				<a href="javascript:void(0)" onclick="gobackemail()"> ou entre com outro email</a>
			</span>
		</h2>
	</div>
	<div class="content-tab-moip">
		<form id="form-loggin" tabindex="-1" action="<?php echo $this->getUrl('onestepcheckout/index/authenticate') ?>" method="POST" class="form-vertical">
			<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" class="input-hidden">
			<div class="form-group">
				<label for="login-email" class="control-label"><?php echo $this->__('Email') ?></label>
				<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
					<input type="email"  name="login[username]" id="login-email" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" class="form-control input-text validate-email" placeholder="<?php echo $this->__('Email') ?>"/>
				</div>
				
			</div>
			<div class="form-group">
				<label for="login-password" class="control-label"><?php echo $this->__('Password') ?></label>
				<input type="password"  name="login[password]" id="login-password"  class="form-control input-text required-entry" placeholder="<?php echo $this->__('Password') ?>"  data-toggle="password"/>
				<p>
					<small>
						<a  href="#" data-toggle="modal" data-target="#EsqueceuSenha"  class="f-left link-recuperar-senha">
							<?php echo $this->__('Forgot your password?') ?>
						</a>
					</small>
				</p>
			</div>
			<div class="error-login"></div>
			<button class="btn btn-secondary btn-success"  title="Entrar" onclick="Authenticate()" type="button" name="submit">
				<span><span>Entrar</span></span>
			</button>
		</form>
	</div>
</div>