<?php $islogin=0; if(Mage::getSingleton('customer/session')->isLoggedIn()) $islogin=1; ?>
<?php $customer = Mage::getSingleton('customer/session')->getCustomer(); ?>
<?php $name = $customer->getFirstname(); ?>
<form id="onestep_form" autocomplete="off" action="<?php echo $this->getUrl('onestepcheckout/index/updateordermethod') ?>" method="POST" class="scaffold-form">
	 <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" class="input-hidden">
	<div class="row">
		<div class="col-sm-3" id="address-info">
			<div class="page-title">
				<h2>Endereço</h2>
			</div>
			<div id="endereco-de-envio">
				<?php echo $this->getChildHtml('shipping',false,true);?>
			</div>
			<div id="endereco-de-cobranca">
				 <label>
				    <input type="checkbox" name="billing[use_for_shipping]" value="1" onchange="viewAddressBilling(this.checked)" checked autocomplete="off"> Usar o mesmo endereço de entrega
				 </label>
				<div class="address-billing-view no-display">
					<?php echo $this->getChildHtml('billing',false,true);?>
				</div>
			</div>
			<?php if(Mage::getStoreConfig('onestepcheckout/layout/allowcoupon')):?>
				<div id="cupom">
					<?php echo $this->getChildHtml('coupon',false,true);?>
				</div>
			<?php endif; ?>
			
			<?php if(Mage::getStoreConfig('onestepcheckout/layout/enable_giftmessage')):?>
				<div id="embalagem">
					<?php echo $this->getChildHtml('additional',false,true) ?>
				</div>
			<?php endif; ?>
		</div>
	
		<div class="col-sm-6">
			
			<?php if(!Mage::helper('onestepcheckout')->onlyProductDownloadable()):?>
				<div id="meio-de-envio">
					<?php echo $this->getChildHtml('shipping_method',false,true);?>
				</div>
			<?php endif?>
			<div class="clearfix" id="checkout-payment-method-load"></div>
			<div class="clearfix" id="meio-de-pagamento">
				<?php echo $this->getChildHtml('payment',false,true);?>
		    </div>

		    

		</div>
    
    	<div class="col-sm-3" id="tabela-de-produtos">
			<div class="hidden-md hidden-lg">
	        	<div id="onestepcheckout_place_order_button">
	                <button type="button" title="<?php echo $this->__('Place Order') ?>" class="btn btn-success btn-lg btn-block moip-place-order" id="checkout-onepage-buttom">
	                        <span><span><?php echo $this->__('Place Order') ?> <i class="fa fa-arrow-right"></i></span></span>
	                </button>
	          	</div>
	        </div>
			<div class="page-title">
				<h2><strong>Pedido</strong></h2>
			</div>
			<div id="review">
				<?php echo $this->getChildHtml('review',false,true);?>	
			</div>
			<div id="totals">
				<?php echo $this->getChildHtml('totals',false,true);?>
			</div>
			<div class="actions-fixed">
				<?php echo $this->getChildHtml('agreements',false,true) ?>
	            
	            <?php if(Mage::getStoreConfig('onestepcheckout/layout/enable_messagetosystem')):?>
	                    <div class="onestepcheckout-comments">
	                        <label for="id_comments" class="checkbox-review"><?php echo $this->__('Comentários do Pedido:');?></label><br/>
	                        <textarea id="id_comments" name="onestepcheckout_comments" class="form-control" cols="40" rows="4"></textarea>
	                    </div>
	            <?php endif;?>
	        	<div id="onestepcheckout_place_order_button">
	                    <button type="button" title="<?php echo $this->__('Place Order') ?>" class="btn btn-success btn-lg btn-block moip-place-order" id="checkout-onepage-buttom">
	                        <span><span><?php echo $this->__('Place Order') ?></span></span>
	                    </button>
	          	</div>
	          	<?php if(Mage::getStoreConfig('onestepcheckout/layout/secure')): ?>
					<div class="selos-seguranca">
						<div class="secure-info">
							<?php echo Mage::getStoreConfig('onestepcheckout/layout/block_selos'); ?>
						</div>
					</div>
				<?php endif; ?>
	        </div>
		</div>
    </div>
</form>

<div class="modal fade" id="new-address" tabindex="-1" role="dialog" aria-labelledby="Novo Endereço" aria-hidden="true" data-keyboard="false">
	<div class="vertical-center-moip">
		<div class="modal-dialog">
		    <div class="modal-content">
		      		<form id="form-new-address" autocomplete="off" action="<?php echo $this->getUrl('onestepcheckout/index/formPostAddress') ?>" method="POST" class="valid-form scaffold-form">
						<div id="form-edit-address" data-url-action="onestepcheckout_index_address_edit">
						</div>
		      		</form>
		    </div>
		</div>
	</div>
</div>



		
<?php if(!$islogin):?>
	<div class="modal fade " id="loginModel" tabindex="-1" role="dialog" aria-labelledby="smallModal" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h4 >Entrar</h4>
	      </div>
	      <div class="modal-body">
	        		<?php echo $this->getChildHtml('login',false,true);?>
	      </div>
	      <div class="modal-footer">
		        <button type="button" class="button btn btn-danger" data-dismiss="modal">Cancelar</button>
  				<button class="btn btn-lg btn-success"  title="Entrar" onclick="onepageLoginPre(this)" type="button" name="pre-login"><span><span>Entrar</span></span></button>
	      </div>
	    </div>
	  </div>
	</div>

	<div class="modal fade " id="EsqueceuSenha" tabindex="-1" role="dialog" aria-labelledby="smallModal" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h4 >Recuperar Senha</h4>
	      </div>
	      <div class="modal-body">
	        		<?php echo $this->getChildHtml('forgotpassword',false,true);?>
	      </div>
	       <div class="modal-footer">
	            <button type="button" class="btn btn-danger" data-dismiss="modal" id="close-forgetpassord" aria-hidden="true">Voltar para página de login</button>
		           <button id="btforgotpass" type="button" onclick="onepageforgotpassword(this)" title="<?php echo $this->__('Enviar') ?>" class="btn btn-success"><span ><span><?php echo $this->__('Enviar') ?></span></span></button>
	            
	    </div>
	  </div>
	</div>
<?php endif; ?>

<div class="modal fade" id="modal-loading-process" tabindex="-1" role="dialog" data-toggle="modal" aria-labelledby="smallModal" aria-hidden="true">
  <div class="vertical-center-moip">
  		<div class="modal-dialog">
	        <div class="progress" id="moip-loading">
	          <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
	            Por favor, aguarde...
	          </div>
	        </div>
  		</div>
	</div>
</div>
