<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form method="post" id="form-validate" >
	<div class="fieldset" >
		<p><?php echo $this->__('Por favor, informe o email. Será encaminhado um link para o seu email com a nova senha.')?></p>
		<ul class="form-list">
			<li >
				<label for="email_address" class="required"><?php echo $this->__('Email Address');?> <em >* </em> </label>
				<div class="input-box" >
					 <input type="text"  name="email" alt="email" id="email_address" class="input-text required-entry validate-email cp-email-recuperar-senha" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
					<div  id="errorforgotpass" class="validation-advice"><?php echo $this->__('Invalid email!');?></div>
				</div>
			</li>
		</ul>
	</div>
	<div class="buttons-set" >
		<span  id="forgotpass-please-wait" class="please-wait">
			<img class="v-middle" title="Loading next step..." alt="Loading next step..." src="<?php echo $this->getSkinUrl('/MOIP/onestepcheckout/images/opc-ajax-loader.gif') ?>"><?php echo $this->__('Loading...');?>
		</span>
		<button id="btforgotpass" type="button" onclick="onepageforgotpassword(this)" title="<?php echo $this->__('Submit') ?>" class="button"><span ><span><?php echo $this->__('Submit') ?></span></span></button>
		 <button type="button" class="no-button" data-dismiss="modal" aria-hidden="true">Voltar para página de login</button>
	 </div>
</form>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function onepageforgotpassword(button)
    {
        if(dataForm.validator && dataForm.validator.validate()){
		   updateForgotpassword(jQuery('#email_address').val());
        }
		jQuery('#errorforgotpass').css('display','none');
    }
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
jQuery('#forgotpass-please-wait').css('display','none');
jQuery('#errorforgotpass').css('display','none');
function updateForgotpassword(email) {
	jQuery('#btforgotpass').css('display','none');
	jQuery('#forgotpass-please-wait').css('display','block');
	jQuery.ajax({
		type: "POST",
		url: "<?php echo Mage::getUrl('onestepcheckout/index/forgotpass')?>",
		data: "email="+email,
		success: function(msg){
				
					jQuery('#form-validate').html("<h2>O email de recuperaçao de senha foi enviado.</h2><button type='button' class='buttons-set' data-dismiss='modal' aria-hidden='true'>Voltar para página de login</button>");


			}
	});
}
//]]>
</script>