<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form method="post" id="form-forgotpass" class="form-forgotpass" tabindex="-1" action="<?php echo Mage::getUrl('onestepcheckout/index/forgotpass')?>">
	
		<p><?php echo $this->__('Por favor, informe o email.')?></p>
		
				<label for="email_address" class="required"><?php echo $this->__('Email Address');?> <em >* </em> </label>
				<div class="input-box" >
					 <input type="email"  name="email"  id="email_address" class="input-text required-entry validate-email" />
						<div  id="errorforgotpass" class="validation-advice no-display"><?php echo $this->__('Invalid email!');?></div>
				</div>
		
	
	
</form>
<div id="callback-forgotpass">
	
</div>

<script type="text/javascript">

    var dataForm = new VarienForm('form-forgotpass', true);
    function onepageforgotpassword(button)
    {
    	console.log(dataForm.validator.validate())
        if(dataForm.validator.validate()){
		   updateForgotpassword(jQuery('#email_address').val());
		   jQuery('.form-forgotpass').css('display','none');
        } else {
        	jQuery('#errorforgotpass').css('display','block');
        }
		
    }

</script>
<script type="text/javascript">

function updateForgotpassword(email) {
	jQuery('#btforgotpass').css('display','none');
	
	jQuery.ajax({
		type: "POST",
		url: "<?php echo Mage::getUrl('onestepcheckout/index/forgotpass')?>",
		data: "email="+email,
		success: function(msg){
				
					jQuery('#callback-forgotpass').html("<h2>O email com uma nova senha foi enviado.</h2><button type='button' class='btn btn-success' data-dismiss='modal' aria-hidden='true'>Voltar para página de login</button>");


			}
	});
}

</script>