<script type="text/javascript" src="https://assets.moip.com.br/v2/moip.min.js"></script>
<script type="text/javascript">
	jQuery.noConflict();
	(function($) {
		jQuery(document).ready(function(){
		 	Validation.creditCartTypes.set('DC', [new RegExp('^3(?:0[0-5]|[68][0-9])[0-9]{11}$'), new RegExp('^[0-9]{3}$'), true]);
	     	Validation.creditCartTypes.set('EO', [false, new RegExp('^([0-9]{3}|[0-9]{4})?$'), false]);
	        Validation.creditCartTypes.set('HI', [false, new RegExp('^([0-9]{3}|[0-9]{4})?$'), false]);
	        Validation.creditCartTypes.set('HP', [false, new RegExp('^([0-9]{3}|[0-9]{4})?$'), false]);
	   });	
	})(jQuery);
</script>