<?php
    $methods = $this->getMethods();
    $oneMethod = count($methods) <= 1;
    $temp = $this->getQuote()->getPayment()->getMethod();
    if(!$temp){
        $temp = "moip_cc";
    }
?>
<div id="co-payment-form">
        <?php foreach($this->getQuote()->getAllItems() as $_item){
           if($_item->getProduct()->isRecurring()){
             $is_recurring = 1;
             $temp = "moip_ccrecurring";
           } else {
             $is_recurring = !1;
           }
        }
        ?>
        <div class="col-sm-2 btn-inputs-payment p-0" data-toggle="buttons" >
                <?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>

                    <?php 
                        $icon_method = array(
                            "moip_cc" => '<span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span>',
                            'moip_ccrecurring' => '<span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span>',
                            "moip_boletorecurring" => '<span class="glyphicon glyphicon-barcode" aria-hidden="true"></span>',
                            "moip_boleto" => '<span class="glyphicon glyphicon-barcode" aria-hidden="true"></span>',
                            "moip_tef" => '<span class="glyphicon glyphicon-usd" aria-hidden="true"></span>',
                            "default" => '<span class="glyphicon glyphicon-usd" aria-hidden="true"></span>'
                            );
                    ?>
                        <label class="btn btn-block btn-group btn-default btn-payment-available <?php echo ($_code == $temp ? "active" : "") ?> <?php echo ($_code == "moip_ccrecurring" ? "active" : "") ?>">
                            <?php if( sizeof($this->getMethods()) > 1 ): ?>
                                <input id="p_method_<?php echo $_code ?>"  value="<?php echo $_code ?>" type="radio" name="payment[method]" title="Meio de Pagamento" onclick="payment.switchMethod('<?php echo $_code ?>');" class="radio payment_method_handle validate-one-required-by-name" <?php echo ($_code == $temp ? "checked" : "") ?> <?php echo ($_code == "moip_ccrecurring"? "checked" : "") ?>/>
                            <?php else: ?>
                               
                               
                                     <input id="p_method_<?php echo $_code ?>"  value="<?php echo $_code ?>" type="radio" name="payment[method]" title="Meio de Pagamento" onclick="payment.switchMethod('<?php echo $_code ?>');" class="radio payment_method_handle validate-one-required-by-name"  <?php echo ($_code == $temp ? "checked" : "") ?> <?php echo ($_code == "moip_ccrecurring"? "checked" : "") ?>/>
                               
                            <?php endif; ?>
                            
                               <div class="icon-payment"><?php echo(isset($icon_method[$_code])? $icon_method[$_code] : $icon_method['default']) ?></div>
                               <div class="text-payment"><?php echo $_method->getTitle() ?></div>
                                
                               <!--  <?php echo($_code == "moip_boleto" ? '<span class="badge">-7%</span>' : ""); ?> -->
                        </label>
                    
                    <?php $html[] = $this->getPaymentMethodFormHtml($_method); ?>
                <?php endforeach; ?>
        </div>
        <div class="col-sm-10 p-0">
                <div class="bg-payment-method">
                        <?php foreach ($html as $_form): ?>
                            <?php echo $_form; ?>
                        <?php endforeach; ?>
                </div>
        </div>
  </div>     
       <?php if( Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
           <script type="text/javascript">
                var payment = new Payment('co-payment-form', '<?php echo $this->getUrl("checkout/onepage/savePayment") ?>');
                    payment.init();
                    PayamentChange();
                    
                    payment.switchMethod('<?php echo $temp; ?>');
                    
            </script>
        <?php endif; ?>

 
