  <div class="min-content-create-account">
   	<div class="col-md-8 col-md-offset-2">
   		<div class="vertical-center-moip">
     			<div class="tabs-checkout">
        			<div id="checkout-Tab" class="tab-content row create-account-tabs">
  					<div class="tab-pane fade active in" id="identifique">
  						<?php echo $this->getTypeLayoutForm(); ?>
  					</div>
  					<div class="tab-pane fade" id="create-loggin">	
  						<div id="isCustomer"></div>						
  					</div>
  					<div class="tab-pane fade" id="create-account">
  						<div id="not-isCustomer"></div>
  					</div>
  				</div>
  			</div>
  		</div>
  	</div>   
  </div>


  <div class="modal fade" id="modal-loading-process" tabindex="-1" role="dialog" data-toggle="modal" aria-labelledby="smallModal" aria-hidden="true">
    <div class="vertical-center-moip">
        <div class="modal-dialog">
          <div class="progress" id="moip-loading">
            <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
              Por favor, aguarde...
            </div>
          </div>
        </div>
    </div>
  </div>


  <div class="modal fade" id="loginModel" tabindex="-1" role="dialog" data-toggle="modal" aria-labelledby="smallModal" aria-hidden="true">
    <div class="vertical-center-moip">
     <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="myModalLabel">Entrar</h4>
        </div>
        <div class="modal-body">
          		<?php echo $this->getChildHtml('login',false,true);?>
        </div>
        <div class="modal-footer">
  	           <button type="button" class="btn btn btn-danger" data-dismiss="modal">Usar outro Email</button>
               <button class="btn btn-secondary btn-success"  title="Entrar" onclick="Authenticate()" type="button" name="submit">
                  <span><span>Entrar</span></span>
                </button>
        </div>
      </div>
    </div>
    </div>
  </div>

   

  <div class="modal fade" id="EsqueceuSenha" tabindex="-1" role="dialog" data-toggle="modal" aria-labelledby="smallModal" aria-hidden="true">
    <div class="vertical-center-moip">
     <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="myModalLabel">Recuperar Senha</h4>
        </div>
        <div class="modal-body">
          		<?php echo $this->getChildHtml('forgotpassword',false,true);?>
        </div>
        <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-dismiss="modal" id="close-forgetpassord" aria-hidden="true">Voltar para página de login</button>
  	           <button id="btforgotpass" type="button" onclick="onepageforgotpassword(this)" title="<?php echo $this->__('Enviar') ?>" class="btn btn-success"><span ><span><?php echo $this->__('Enviar') ?></span></span></button>
              
        </div>
      </div>
    </div>
    </div>
  </div>

 
