
<form id="onestep_form_account" action="<?php echo $this->getUrl('onestepcheckout/index/CreataAccountInit') ?>" method="POST" class="scaffold-form" tabindex="-1">

    

    

    <?php echo $this->getBlockHtml('formkey') ?>
    <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat')->setTemplate('MOIP/customer/widget/taxvat.phtml');  ?>
    <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob')->setTemplate('MOIP/customer/widget/dob.phtml'); ?>

    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" class="input-hidden">
    <input type="hidden" name="billing[address_id]" id="billing:address_id" class="input-hidden">
    <input type="hidden" name="billing[register_new_account]" value="1" title="Criar conta" id="register_new_account" class="input-hidden">
    <input type="hidden" name="billing[confirm_password]"  id="billing:confirm_password" class="input-hidden">
    <input type="hidden" name="billing[save_in_address_book]" value="1" />
    
            <div class="col-sm-6">
                <div class="row">
                    <div class="form-group">
                        <label for="billing:email" class="col-sm-12 control-label"><em>*</em>Endereço de Email</label>
                            <div class="col-sm-12">
                                <input   type="email" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="Endereço de e-mail" class="input-moip form-control validate-email required-entry" >
                            </div>
                    </div>
                </div>
            </div>
            

        
            
            <div class="col-sm-6">
                <div class="row">
                    <div class="form-group">
                        <label for="billing:customer_password" class="col-sm-12 control-label"><em>*</em>Crie sua Senha</label>
                        <div class="col-sm-12">
                            <input type="password" name="billing[customer_password]" id="billing:customer_password" title="Senha" class="input-moip form-control  required-entry validate-password"  data-toggle="password">
                        </div>
                    </div>
                </div>
            </div>
     
            <div class="clearfix"></div>
            <div class="col-sm-12">
                    <hr>
            </div>
           <div class="clearfix"></div>
         <?php if(Mage::getStoreConfig('onestepcheckout/config/enable_pj')):?>
            <div class="col-md-8 col-md-offset-2">
                    <div class="row">
                          
                            <label for="radios-inline" class="control-label col-sm-12">Comprar Como:</label>
                            <div class="btn-group btn-group-justified" data-toggle="buttons">  
                                
                                        <label class="btn btn-primary active" data-initialize="radio" for="pf">
                                            <input class="validate-digits" name="billing[tipopessoa]" id="pf" tabindex="-1" type="radio" value="1" checked="checked"> Pessoa Física
                                        </label>
                                   
                                        <label class="btn btn-primary" data-initialize="radio" for="pj">
                                            <input class="validate-digits" name="billing[tipopessoa]" id="pj" tabindex="-1" type="radio" value="0"> Pessoa Jurídica
                                        </label>
                                   
                            </div>
                    </div>
               
                </div>
            <div class="clearfix"></div>
            <div class="col-sm-12 dados-pj">
                  <legend class="dados-pj">Dados do Empresa</legend>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-6 dados-pj">
                <div class="row">
                    <div class="form-group">
                        <label class="col-sm-12 control-label" for="textinput">Nome Fantasia</label>
                        <div class="col-sm-12">
                            <input   type="text" title="Nome Fantasia" class="input-moip form-control " name="billing[nomefantasia]" id="nomefantasia" value="<?php echo $this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getNomefantasia()); ?>" >
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 dados-pj">
                <div class="row">
                    <div class="form-group">
                        <label class="col-sm-12 control-label" for="textinput">Razão social</label>
                        <div class="col-sm-12">
                            <input   type="text" title="razao_social" class="input-moip form-control " name="billing[razaosocial]" id="razaosocial" value="<?php echo $this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getRazaosocial()) ?>" >
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-6 dados-pj">
                <div class="row">
                    <div class="form-group">
                        <label class="col-sm-12 control-label" for="textinput">CNPJ</label>
                        <div class="col-sm-12">
                            <input   type="tel" title="cnpj" class="input-moip form-control" name="billing[cnpj]" id="cnpj" value="<?php echo $this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getCnpj()) ?>" >
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                Validation.add('validar_cnpj', 'O CNPJ informado \xE9 invalido', function(v){
                        return validaCPF(v,0);
                });
                jQuery('#cnpj').mask("00.000.000/0000-00", {placeholder: "__.___.___/____-__"});
            </script>
            
            <div class="col-sm-6 dados-pj">
                <div class="row">
                    <div class="form-group">
                        <label class="col-sm-12 control-label" for="textinput">Inscrição Estadual</label>
                        <div class="col-sm-12">
                            <input   type="text" title="cnpj" class="input-moip form-control " name="billing[insestadual]" id="insestadual" value="<?php echo $this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getInsestadual()) ?>" >
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            
            <div class="col-sm-12">
                <legend class="dados-pj">Dados do Comprador</legend>
            </div>

        <?php endif; ?>
            
           
            <div class="col-sm-6">
                <div class="row">
                    <div class="form-group">
                          <label class="col-sm-12 control-label" for="textinput">Nome</label>  
                          <div class="col-sm-12">
                               <input  type="text" id="billing:firstname" name="billing[firstname]" value="<?php echo  $this->getAddress()->getFirstname() ?>" title="Nome" class="input-moip form-control  required-entry" >
                          </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="row">
                    <div class="form-group">
                          <label class="col-sm-12 control-label" for="textinput">Sobrenome</label>
                          <div class="col-sm-12">
                            <input   type="text" id="billing:lastname" name="billing[lastname]" value="<?php echo  $this->getAddress()->getLastname() ?>" title="Sobrenome" class="input-moip form-control  required-entry" >
                          </div>
                    </div>
                </div>
            </div>

            
            <div class="clearfix"></div>
            
            
            <div class="col-sm-6">
                <div class="row">
                    <div class="form-group">
                        <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="row">
                    <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                </div>
            </div>
        
            <div class="clearfix"></div>
        
       
          
            <div class="col-sm-6">
                <div class="row">
                    <div class="form-group">
                          <label class="col-sm-12 control-label" for="textinput">Telefone</label>  
                          <div class="col-sm-12">
                                <input   type="tel" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>"  title="Telefone" class="input-moip form-control  validate-tel-national required-entry" id="billing:telephone"  >

                          </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="row">
                    <div class="form-group">
                          <label class="col-sm-12 control-label" for="textinput">Celular</label>
                          <div class="col-sm-12">
                                <input   type="tel" name="billing[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>"  title="Celular" class="input-moip form-control  validate-cel-national input-moip form-control " id="billing:fax" >

                          </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-12">
                    <hr>
            </div>
            <div class="clearfix"></div>
            <div class="col-xs-6">
                <div class="row">
                    <div class="form-group">
                          <label class="col-sm-12 control-label" for="textinput">Cep - <a href="http://www.buscacep.correios.com.br/" target="_blank" class="f-right not-zip-code hidden-xs" tabindex="-1">Não sabe o CEP?</a></label>  
                          <div class="col-sm-12">
                                <input   type="tel" title="CEP" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>"  class=" form-control  validate-zip-br  required-entry moipzip" onchange="javascript:buscarEndereco('billing-registrer');"   placeholder="CEP">

                          </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="row">
                    <button type="button" id="singlebutton" tabindex="-1" onclick="javascrip:buscarEndereco('billing-registrer')" name="singlebutton" class="btn btn-default" aria-label="Single Button">Buscar Endereço</button>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="col-sm-6 hide-zip-code">
                <div class="row">
                    <div class="form-group">
                          <label class="col-sm-12 control-label" for="textinput">Rua</label>  
                          <div class="col-sm-12">
                                <input   type="text" title="Endereço da rua" name="billing[street][0]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class=" form-control   required-entry  validate-length minimum-length-4 maximum-length-65" placeholder="Endereço">
                          </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-2 hide-zip-code">
                <div class="row">
                    <div class="form-group">
                          <label class="col-sm-12 control-label" for="textinput">Número</label>
                          <div class="col-sm-12">
                                <input   type="tel" title="Número" name="billing[street][1]" id="billing:street2" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" class=" form-control   required-entry  validate-length minimum-length-1 maximum-length-5" placeholder="Número">
                          </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 hide-zip-code">
                <div class="row">
                    <div class="form-group">
                          <label class="col-sm-12 control-label" for="textinput">Complemento</label>
                          <div class="col-sm-12">
                                <input   type="text" title="Complemento" name="billing[street][2]" id="billing:street3" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(3)) ?>" class=" form-control   validate-length minimum-length-1 maximum-length-30" placeholder="Complemento">
                          </div>
                    </div>
                </div>
            </div>

            <div class="clearfix"></div>
            <div class="col-sm-6 hide-zip-code">
                <div class="row">
                    <div class="form-group">
                        <label class="col-sm-12 control-label" for="textinput">Bairro</label>
                        <div class="col-sm-12">
                            <input   type="text" title="Bairro" name="billing[street][3]" id="billing:street4" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(4)) ?>" class=" form-control  required-entry  validate-length minimum-length-1 maximum-length-60" placeholder="Bairro">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 hide-zip-code">
                <div class="row">
                    <div class="form-group">
                        <label class="col-sm-12 control-label" for="textinput">Cidade</label>
                        <div class="col-sm-12">
                            <input   type="text" title="Cidade" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>"class=" form-control   required-entry" id="billing:city" placeholder="Cidade">
                        </div>
                    </div>
                </div>
            </div>

            <div class="clearfix"></div>
            <div class="col-sm-6 hide-zip-code">
                <div class="row">
                    <div class="form-group">
                        <label class="col-sm-12 control-label" for="textinput">Estado</label>
                        <div class="col-sm-12">
                                <select id="billing:region_id" name="billing[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select form-control">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>

                                <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class=" form-control  <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 hide-zip-code"">
                <div class="row">
                    <div class="form-group">
                            <label class="col-sm-12 control-label" for="textinput">País</label>
                            <div class="col-sm-12">
                                 <?php echo $this->getCountryHtmlSelect('billing') ?>
                            </div>
                    </div>
                </div>
            </div>
            
            <div class="clearfix"></div>
        <div class="col-sm-12">
            <hr>
        </div>  
        
        
        
        
        
        <div class="col-sm-12">
            <button type="submit" id="init-account" class="btn btn-success btn-block btn-arround bnt-lg"><span><span>Criar Conta</span></span></button>
        </div>


</form>


<script type="text/javascript">
    var billingRegionUpdater = new RegionUpdater("billing:country_id", "billing:region", "billing:region_id", countryRegions, undefined, "billing:postcode");
    jQuery("#billing\\:country_id").addClass('form-control');
    jQuery('#billing\\:taxvat').addClass('validar_cpf');
    jQuery('#billing\\:region_id').attr('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
    Validation.add('validar_cpf', 'O CPF informado \xE9 invalido', function(v){
            return validaCPF(v,0);
    });
    Validation.add('validate-tel-national', 'Entre com telefone válido: (99)9999-9999 ou caso tenha o 9º digito (99)9999-99999', function(v) {
            return Validation.get('IsEmpty').test(v) || /^([()])([0-9]){2}([)])([0-9]){4}([-])([0-9]){4,5}$/.test(v);
        });

    Validation.add('validate-cel-national', 'Entre com telefone válido: (99)9999-9999 ou caso tenha o 9º digito (99)9999-99999', function(v) {
        return Validation.get('IsEmpty').test(v) || /^([()])([0-9]){2}([)])([0-9]){4}([-])([0-9]){4,5}$/.test(v);
    });
    Validation.add('validate-zip-br', 'Entre com um cep válido: 99999-999', function(v) {
        return Validation.get('IsEmpty').test(v) || /^([0-9]){5}([-])([0-9]){3}$/.test(v);
    });
    jQuery(document).ready(function(){
        jQuery('#onestep_form :input').blur(function() {
                            Validation.validate(jQuery(this).attr('id'));
        });
    });
</script>
