<h4 class="sub-title-method">
	<div class="onestepcheckout-numbers onestepcheckout-numbers-1" id="moip-osc-p1"></div><?php echo $this->__('Meio de Envio') ?>
</h4>
<div id="co-shipping-method-form" >	
    <div id="checkout-shipping-method-load"> 
        <?php echo $this->getChildHtml('available') ?>
    </div>	
    <script type="text/javascript">
    //<![CDATA[
        var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
    //]]>
    </script>
</div>

