<?php if ($this->getTotals()): ?>
   
    <div id="view-table-prices" class="">
        <table class="table">
        	<tfoot class="foot-table-review ">
    		    <?php $_colspan = 1; ?>
    		    <?php echo $this->renderTotals(null, $_colspan); ?>
    		</tfoot>
        </table>
    </div>
    <div class="grand-total">
        <?php echo $this->renderTotals('footer', 1); ?>
    </div>
<?php endif; ?>

