<?php if(Mage::getStoreConfig('moipall/oneclick_config/enable_oneclick', Mage::app()->getStore())): ?>
	<button type="button"  onclick="productAddToCartForm.submitOneclickbuy(this)" class="btn btn-lg btn-success btn-block btn-oneclickbuy">
    <span>
        <span>
            <i class="fa fa-mouse-pointer"></i> Comprar em 1 clique
        </span>
    </span>
</button>
<span id='ajax_loader_product' style="display:none"><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>

<?php endif; ?>