<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<script type="text/javascript">
var form_post_address  			= "<?php echo Mage::getUrl('onestepcheckout/index/formPostAddress')?>";
var url_new_address  			= "<?php echo Mage::getUrl('onestepcheckout/index/NewAddress')?>";
var url_busca_cep 				= "<?php echo Mage::getUrl('onestepcheckout/index/buscaCep') ?>";
var address_status = "<?php echo Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling() ?>";
var customer_status = "<?php echo Mage::getSingleton('customer/session')->isLoggedIn() ?>";
var url_success_action_redirect = "<?php echo Mage::getUrl('checkout/onepage')?>";
 


	jQuery(document).ready(function(){
		AddValidateFormCreate();
		
		Setmask();
		
	});	

</script>

