<table cellpadding="0" class="moip-links-details" align="center" width="100%">
	<tr align="center" width="100%"> 
		<td align="center" width="100%" >
			<?php $_order=$this->getOrder() ?>
			<?php if($this->getState() == "holded"): ?>
				<?php $moip = $this->getDataMoip() ?>
				<?php if($this->getTypePayment() == "boleto"): ?>
					<a href="<?php echo $moip["moip_href_boleto"]; ?>/print" class="btn btn-action btn-success" style="
                        background: #6bc352;
                        background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJod…EiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
                        background: -moz-linear-gradient(top,#6bc352 0%,#57a244 100%);
                        background: -webkit-gradient(linear,left top,left bottom,color-stop(0%,#6bc352),color-stop(100%,#57a244));
                        background: -webkit-linear-gradient(top,#6bc352 0%,#57a244 100%);
                        background: -o-linear-gradient(top,#6bc352 0%,#57a244 100%);
                        background: -ms-linear-gradient(top,#6bc352 0%,#57a244 100%);
                        background: linear-gradient(to bottom,#6bc352 0%,#57a244 100%);
                        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#6bc352',endColorstr='#57a244',GradientType=0);
                        background-repeat: repeat-x;
                        border-color: #3e8f3e;
                        text-shadow: 0 -1px 0 rgba(0,0,0,0.2);
                        -webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,0.15), 0 1px 1px rgba(0,0,0,0.075);
                        box-shadow: inset 0 1px 0 rgba(255,255,255,0.15), 0 1px 1px rgba(0,0,0,0.075);
                            padding: 10px 16px;
                        font-size: 18px;
                        line-height: 1.33;
                        border-radius: 0;
                        color: #fff;
                        background-color: #5cb85c;
                        border-color: #4cae4c;"
                    >
						Imprimir o Boleto
					</a>
				<?php endif; ?>
				<?php if($this->getTypePayment() == "tef"): ?>
    				<a href="<?php echo $moip["moip_href_trans"]; ?>" class="btn btn-action btn-success" style="
                        background: #6bc352;
                        background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJod…EiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
                        background: -moz-linear-gradient(top,#6bc352 0%,#57a244 100%);
                        background: -webkit-gradient(linear,left top,left bottom,color-stop(0%,#6bc352),color-stop(100%,#57a244));
                        background: -webkit-linear-gradient(top,#6bc352 0%,#57a244 100%);
                        background: -o-linear-gradient(top,#6bc352 0%,#57a244 100%);
                        background: -ms-linear-gradient(top,#6bc352 0%,#57a244 100%);
                        background: linear-gradient(to bottom,#6bc352 0%,#57a244 100%);
                        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#6bc352',endColorstr='#57a244',GradientType=0);
                        background-repeat: repeat-x;
                        border-color: #3e8f3e;
                        text-shadow: 0 -1px 0 rgba(0,0,0,0.2);
                        -webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,0.15), 0 1px 1px rgba(0,0,0,0.075);
                        box-shadow: inset 0 1px 0 rgba(255,255,255,0.15), 0 1px 1px rgba(0,0,0,0.075);
                            padding: 10px 16px;
                        font-size: 18px;
                        line-height: 1.33;
                        border-radius: 0;
                        color: #fff;
                        background-color: #5cb85c;
                        border-color: #4cae4c;"
                    >
						Realizar Transferência
					</a>
				<?php endif; ?>
			<?php elseif($this->getState() == "canceled"): ?>
				<?php $link = Mage::getUrl('sales/order/reorder/'); ?>
			    <?php $link = $link.'order_id/'.$_order->getId(); ?>
				<a href="<?php echo $link; ?>" class="btn btn-action btn-success" 
                style="
                        background: #6bc352;
                        background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJod…EiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
                        background: -moz-linear-gradient(top,#6bc352 0%,#57a244 100%);
                        background: -webkit-gradient(linear,left top,left bottom,color-stop(0%,#6bc352),color-stop(100%,#57a244));
                        background: -webkit-linear-gradient(top,#6bc352 0%,#57a244 100%);
                        background: -o-linear-gradient(top,#6bc352 0%,#57a244 100%);
                        background: -ms-linear-gradient(top,#6bc352 0%,#57a244 100%);
                        background: linear-gradient(to bottom,#6bc352 0%,#57a244 100%);
                        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#6bc352',endColorstr='#57a244',GradientType=0);
                        background-repeat: repeat-x;
                        border-color: #3e8f3e;
                        text-shadow: 0 -1px 0 rgba(0,0,0,0.2);
                        -webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,0.15), 0 1px 1px rgba(0,0,0,0.075);
                        box-shadow: inset 0 1px 0 rgba(255,255,255,0.15), 0 1px 1px rgba(0,0,0,0.075);
                            padding: 10px 16px;
                        font-size: 18px;
                        line-height: 1.33;
                        border-radius: 0;
                        color: #fff;
                        background-color: #5cb85c;
                        border-color: #4cae4c;"
                    >
                
						Tentar novamente
				</a>
			<?php endif; ?>
		</td>
	</tr>

</table>
