<?php if(Mage::app()->getRequest()->getControllerModule() != "Mage_Checkout" && Mage::app()->getRequest()->getActionName() != "progresscheckout"): ?>
	<?php $info = $this->_prepareInfo(); ?>
	<div class="box-content">
		<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
		<p><a  class="button btn-checkout btn-default" title="Finalizar compra"  href="<?php echo  $info['moip_href_boleto']  ?>"  target="_blank" style="max-width: 200px;">Imprimir Boleto</a></p>
		<p>Código de Barras</p>
		<p><input type="text" value="<?php echo $info['moip_linecode_boleto'] ?>" readonly="disable" style="max-width: 200px; white-space: nowrap;overflow: hidden;text-overflow: ellipsis;"></p>
		<p>Vencimento: <?php echo date('d-m-Y', strtotime($info['moip_expiration_boleto'])) ?></p>
	</div>
<?php else: ?>
	Pagamento via Boleto
<?php endif; ?>

