<?php
/* Mage::getModel("sales/order")->getCollection()->getLastItem()->getIncrementId(); */
if(Mage::app()->getRequest()->getModuleName() != "onestepcheckout" && Mage::app()->getRequest()->getModuleName() != "checkout"){
?>
		<?php $info = $this->_prepareInfo(); ?>


		<div class="box-content">
			<h3><?php echo $info['moip_card_brand']; ?> <b><?php echo $info['moip_card_installment']; ?><b> parcelas</h3>
			<div class="input-value">
				<?php echo $info['moip_card_fullname'] ?>
			</div>

			<div class="input-value">
				<label>6 Primeiros dígitos do cartão</label>
				<?php echo $info['moip_card_first6'] ?>
			</div>

			<div class="input-value">
				<label>4 Últimos dígitos do cartão</label>
				<?php echo $info['moip_card_last4'] ?>
			</div>


			
			<div class="input-value">
				<label>Pagamento n.º</label>
				<?php echo $info['moip_pay'] ?>
			</div>

		</div>

	

<?php } else { ?>

<?php $addtional = $this->getMethod()->getInfoInstance()->getAdditionalData();?>
<?php $addtional = unserialize($addtional); ?>

	<?php echo Mage::helper('transparente')->__('Nome Impresso no cartão: %s', $this->htmlEscape($this->getInfo()->getCcOwner())) ?><br/>
	<?php echo Mage::helper('transparente')->__('Bandeira: %s', $this->htmlEscape($this->getInfo()->getCcType())) ?><br/>
	<?php echo Mage::helper('transparente')->__('Número do cartão: xxxx-%s', $this->htmlEscape($this->getInfo()->getCcLast4())) ?><br/>
	<?php echo Mage::helper('transparente')->__('Vencimento do cartão: %s/%s', $this->htmlEscape($this->getInfo()->getCcExpMonth()), $this->htmlEscape($this->getInfo()->getCcExpYear())) ?><br/>
<?php } ?>