
<?php if(Mage::app()->getRequest()->getControllerModule() != "Mage_Checkout" && Mage::app()->getRequest()->getActionName() != "progresscheckout"): ?>

		<div class="box-content">
			<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
			<?php $url = $this->getMoipTransfHref(); ?>
			<?php if(isset($url)): ?>	
				<div>
					<a  class="button btn-checkout btn-default" title="Finalizar compra"  href="<?php echo  $url ?>"  target="_blank">
						<?php echo Mage::helper('transparente')->__('Ir para o site do banco %s', $this->getNameBank()); ?>
					</a>
				</div>
			<?php else: ?>
					<div>
						<?php echo Mage::helper('transparente')->__('Não foi possível recuperar a informação do pagamento.'); ?>
					 </div>
			<?php endif; ?>
		</div>
<?php elseif( Mage::app()->getRequest()->getActionName() == "success"): ?>
		<div class="box-content">
				<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
				<?php $url = $this->getMoipTransfHref(); ?>
				<?php if(isset($url)): ?>	
					<div>
						<a  class="button btn-checkout btn-default" title="Finalizar compra"  href="<?php echo  $url ?>"  target="_blank">
							<?php echo Mage::helper('transparente')->__('Ir para o site do banco %s', $this->getNameBank()); ?>
						</a>
					</div>
					
				<?php else: ?>
						<div>
							<?php echo Mage::helper('transparente')->__('Não foi possível recuperar a informação do pagamento.'); ?>
						 </div>
				<?php endif; ?>
			</div>
<?php else: ?>
		<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<?php endif; ?>