<?php if(Mage::app()->getRequest()->getControllerModule() != "Mage_Checkout" && Mage::app()->getRequest()->getActionName() != "progresscheckout"): ?>
<?php $info = $this->_prepareInfo(); ?>
<div class="box-content">
	
	<a  class="btn btn-checkout btn-default" title="Finalizar compra"  href="<?php echo  $info['moip_href_trans']  ?>"  target="_blank">
		<span><span>Pagar agora</span></span>
	</a>
</div>
<?php elseif( Mage::app()->getRequest()->getActionName() == "success"): ?>
	<?php $info = $this->_prepareInfo(); ?>
	<p><a  class="button btn-checkout btn-default" title="Finalizar compra"  href="<?php echo  $info['moip_href_trans']  ?>"  target="_blank">Pagar agora</a></p>
<?php else: ?>
	Pagamento via Transf. Eletrônica
<?php endif; ?>
