<?php $_code=$this->getMethodCode() ?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none">

	<div class="recommendation">
		<ul class="checkout-info-admin">
			<li class="checkout-info-item"><p class="checkout-info-text"><?php echo Mage::helper('transparente')->__('Por razões de segurança da web não permitido obter os dados de cartão do cliente.') ?></p></li>
			<li class="checkout-info-item"><p class="checkout-info-text"><?php echo Mage::helper('transparente')->__('Você deverá concluir a transação e informar que o cliente receberá um email com link de pagamento') ?></p></li>
			<li class="checkout-info-item"><p class="checkout-info-text"><?php echo Mage::helper('transparente')->__('Você poderá acompanha-lo durante todo o processo no então, não solicite dados de cartão do cliente.') ?></p></li>
		</ul>
	</div>

</ul>